"""Generate test fixtures for the pipeline test suite.

Run once::

    python -m pipeline.tests.make_fixtures

Creates ``pipeline/tests/fixtures/test_clip.mkv`` — a 30-second synthetic
MKV with an SMPTE colour-bar pattern (1280x720) and a 1 kHz test tone.
The file is gitignored and must be regenerated by each developer.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

FIXTURES_DIR = Path(__file__).parent / "fixtures"
TEST_CLIP = FIXTURES_DIR / "test_clip.mkv"


def make_test_clip() -> None:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)

    if TEST_CLIP.exists():
        print(f"Already exists: {TEST_CLIP}")
        return

    cmd = [
        "ffmpeg",
        "-y",
        # Video: SMPTE colour bars at 720p, 30 fps, 30 s
        "-f", "lavfi", "-i", "smptebars=size=1280x720:rate=30",
        # Audio: 1 kHz sine wave tone, stereo, 30 s
        "-f", "lavfi", "-i", "sine=frequency=1000:sample_rate=44100",
        "-t", "30",
        # Video codec
        "-c:v", "libx264", "-preset", "ultrafast", "-crf", "28",
        # Audio codec
        "-c:a", "aac", "-b:a", "128k",
        str(TEST_CLIP),
    ]

    print(f"Generating {TEST_CLIP} …")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print("ffmpeg stderr:", result.stderr, file=sys.stderr)
        sys.exit(1)

    size_mb = TEST_CLIP.stat().st_size / 1_048_576
    print(f"Created: {TEST_CLIP}  ({size_mb:.1f} MB)")


if __name__ == "__main__":
    make_test_clip()
